### PR TITLE
Add RcppParallel cxxflags to makevars

### PR DESCRIPTION
**Pull request by andrjohns**
Adds RcppParallel's `CXXFLAGS` to your package makevars, which are needed for compatibility with Windows ARM64

### CODE REVIEW

**Comment by traversc** [comment]
Thanks, maybe this would be good to first bring up in RcppParallel? Do you know why this is necessary in window arm and not elsewhere?

**Comment by andrjohns** [comment]
> Thanks, maybe this would be good to first bring up in RcppParallel? Do you know why this is necessary in window arm and not elsewhere?

This is because the TBB needs different compilation flags for compatibility with windows arm, RcppParallel will provide these flags - your Makevars just needs to request them from RcppParallel

**Comment by traversc** [comment]
I misinterpreted, I see now. Thanks!

**Comment by andrjohns** [comment]
> I misinterpreted, I see now. Thanks!

No worries, thanks!

**Pull request merged**
